### ISSUE TITLE
LDAP autentikazioa Active Directory bidez

### ISSUE THREAD

**Issue by xabikip** [kubbit/gerkud#2]
Kaixo,

Aplikazioa instalatu eta martxan jarri dut. Erabiltzaile eta talde baimenak Active Directory bidez konfiguratu ditut, horretarako LDAPAuth.yml fitxategian LDAp zerbitzariko beharrezko datuak jarriz. Badaukazue gida edo azalpenik nola lotzen diren Active Directoryko erabiltzaile eta taldeak Gerkud aplikazioko erabiltzaile eta taldeekin?

Adibidez, froga egin dut nire LDAPeko erabiltzaileaz eta ikusi dut `sf_guard_user` taulan sortu dela, baina `is_super_admin` eremua 0 baloreakin. Zuzenean datu basean aldatu dut 1 balorea jarriz eta sartzen naiz, baina beste edozein erabiltzailerekin saioa hasten saiatzen banaiz errore mezu hau agertzen da: "Tu usuario no tiene permisos para usar la aplicación."

Erabiltzaile eta taldeen baimenen inguruko azalpen bat ematerik bai?

Eskerrik asko

**Comment by kubbit** [comment]
Gerkud aplikazioak ez du **is_super_admin** eremua erabiltzen. Baimenak erabiltzailearen taldearen arabera bereizten dira:

1. **admins**: super-administratzaileak, beste erabiltzaileei saila esleitzeko aukera dute.
2. **gerkud**: gerkud-eko administratzaileak, gertakarietan baimen guztiak dituzte.
3. **zerbitzu**: saileko langileak, beren saileko gertakariak kudeatu ditzakete.
4. **arrunta**: bestelakoak, gertakari berriak sortu eta iruzkinak gehitzeko baimena dute.

Gerkud eta Active Directory-ko taldeen erlazioa LDAPAuth.yml fitxategian ezartzen da, adibidez:

```yml
groupMappings:
   admins:
     - Domain Administrators
   gerkud:
     - Gerkud Admins
   zerbitzu:
     - Gerkud Zerbitzuak
   arrunta:
     - Domain Users
```

Gerkud-eko eskuliburuan (_web/doc/Eskuliburua_eu.pdf_) taldeen baimenei buruzko informazio gehiago baduzu.

**Comment by xabikip** [comment]
Hauxe da `LDAPAuth.yml` fitxategian jarri dudan taldeen mapeoa:
```
groupMappings:
   zerbitzu:
     - Zerbitzuak
   admins:
     - Administradores de dominio
     - Domain Administrators
     - informatika
   gerkud:
     - Gerkud
   arrunta:
     - Domain Users
     - UsuariosOinati
```

Nire AC-ko erabiltzailea informatika eta Administradores de dominio taldean dago, beraz, ulertzn dudanagatik Gerkud aplikazioan admin rola izan beharko nuke. Hainbat modutara frogak egiten ibili naiz eta beti "Tu usuario no tiene permisos para usar la aplicación" mezua azaltzen da logina egin ondoren (bakarrik **is_super_admin** = 1 jarrita sartu ahal naiz).

Konturatu naiz datu basean taula hauek ez direla sortu (Langilea, Saila eta SailekoLangileak). Zer ikusirik izan dezake honek?
Ez dakit zergaitik, baina `php symfony doctrine:build --all --and-load --no-confirmation` aginduak sortzen duen `data/sql/schema.sql`  fitxategian ez daude taula hauen CREATE aginduak, eta ez dit errorerik botatzen `doctrine:build` aginduak. Pasa ahalko zenidake `data/sql/schema.sql` egoki bat, beharrezkoak diren taula guztiekin?

Eskerrik asko

**Comment by kubbit** [comment]
Aipatutako taulek beste izen bat daukate datu basean:

- Langilea => sf_guard_user
- Saila => sf_guard_group
- SailekoLangileak => sf_guard_user_group

Ematen dizun errorea normalean LDAP-eko taldeekin loturan arazoren bat dagoenean agertzen da. Kasu honetan ez dakit zehazki zein izan daitekeen.

Depuratzeko erabili **developer** modua, adibidez:
http://gerkud.example.org/app_dev.php

Honek erroreari buruzko informazio gehiago erakutsiko dizu, eta log/app_dev.log fitxategian trazak idatziko ditu.

**Comment by xabikip** [comment]
Ados, depuratu dut eta lortu dut sartzea.

Badakizu ACko erabiltzaile bat talde bat baino gehiagotan badago, eta aldi berean, bi talde hauek Gerkudeko talde ezberdinetan gehitauta badaude, zein talderi egiten dion kasu?

Adibidez, erab1 "talde1" eta "talde2" barruan dago ACan. Eta  LDAPAuth.yml fitxategian honela jartzen dut:
```
groupMappings:
   zerbitzu:
     - Zerbitzuak
   admins:
     - talde1
   gerkud:
     - Gerkud
   arrunta:
     - talde2
```
Adibide honetan erab1 zer izango zen "arrunta" edo "admins"?

Eskerrik asko
